version: '3'
services:
  local-ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  streamlit-app:
    image: aitao/openrag:0.1
    ports:
      - 8501:8501

